"""把 website/content 下的 Markdown 课程内容打包成浏览器可读取的 content.js。"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).parent
DOCS = ROOT / "content"
OUTPUT = ROOT / "content.js"


def parse_document(path: Path):
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    metadata = {}
    body = text
    if text.startswith("---\n"):
        _, frontmatter, body = text.split("---\n", 2)
        for line in frontmatter.splitlines():
            if ":" not in line:
                continue
            key, value = line.split(":", 1)
            metadata[key.strip()] = value.strip().strip('"')
    metadata.setdefault("id", path.stem)
    metadata.setdefault("title", path.stem)
    metadata.setdefault("order", "99")
    metadata["order"] = int(metadata["order"])
    metadata["body"] = body.strip()
    return metadata


def main():
    documents = [parse_document(path) for path in sorted(DOCS.rglob("*.md"))]
    documents.sort(key=lambda item: item["order"])
    payload = {
        "meta": {
            "title": "从零开始学 AI",
            "subtitle": "五个项目，从零建立完整 AI 入门路线",
            "version": "0.5.0",
            "githubUrl": "https://github.com/Tadasuki/zero-to-ai-learning",
            "courses": [
                {"id": "course-01", "number": "01", "title": "神经网络识别手写数字", "summary": "输入、权重、激活、损失、反向传播、梯度下降。"},
                {"id": "course-02", "number": "02", "title": "线性回归：让机器学会预测", "summary": "从分类走向连续数值，理解训练集、测试集和过拟合。"},
                {"id": "course-03", "number": "03", "title": "CNN：让网络更会看图片", "summary": "卷积、池化、特征图，以及为什么 CNN 适合图像。"},
                {"id": "course-04", "number": "04", "title": "文本分类：让机器读懂一类话", "summary": "把文字变成向量，用模型判断情感或主题。"},
                {"id": "course-05", "number": "05", "title": "部署 AI 小应用", "summary": "把训练好的模型接到网页，让别人也能使用。"},
            ],
        },
        "documents": documents,
    }
    OUTPUT.write_text(
        "// Generated by build.py. Edit Markdown files in content/ instead.\n"
        "window.COURSE_CONTENT = "
        + json.dumps(payload, ensure_ascii=False)
        + ";\n",
        encoding="utf-8",
    )
    print(f"已生成 {OUTPUT}，收录 {len(documents)} 个文档。")


if __name__ == "__main__":
    main()
